/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as ApiGamesRouteImport } from './routes/api.games'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as ApiGamesGameIdJoinRouteImport } from './routes/api.games.$gameId.join'
import { Route as ApiGamesGameIdSocketRouteImport } from './routes/api.games.$gameId.socket'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoute = ApiGamesRouteImport.update({
  id: '/api/games',
  path: '/api/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdJoinRoute = ApiGamesGameIdJoinRouteImport.update({
  id: '/$gameId/join',
  path: '/$gameId/join',
  getParentRoute: () => ApiGamesRoute,
} as any)
const ApiGamesGameIdSocketRoute = ApiGamesGameIdSocketRouteImport.update({
  id: '/$gameId/socket',
  path: '/$gameId/socket',
  getParentRoute: () => ApiGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/score': typeof ScoreRoute
  '/api/games': typeof ApiGamesRouteWithChildren
  '/game/$gameId': typeof GameGameIdRoute
  '/api/games/$gameId/join': typeof ApiGamesGameIdJoinRoute
  '/api/games/$gameId/socket': typeof ApiGamesGameIdSocketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/score': typeof ScoreRoute
  '/api/games': typeof ApiGamesRouteWithChildren
  '/game/$gameId': typeof GameGameIdRoute
  '/api/games/$gameId/join': typeof ApiGamesGameIdJoinRoute
  '/api/games/$gameId/socket': typeof ApiGamesGameIdSocketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/score': typeof ScoreRoute
  '/api/games': typeof ApiGamesRouteWithChildren
  '/game/$gameId': typeof GameGameIdRoute
  '/api/games/$gameId/join': typeof ApiGamesGameIdJoinRoute
  '/api/games/$gameId/socket': typeof ApiGamesGameIdSocketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/score'
    | '/api/games'
    | '/game/$gameId'
    | '/api/games/$gameId/join'
    | '/api/games/$gameId/socket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/score'
    | '/api/games'
    | '/game/$gameId'
    | '/api/games/$gameId/join'
    | '/api/games/$gameId/socket'
  id:
    | '__root__'
    | '/'
    | '/score'
    | '/api/games'
    | '/game/$gameId'
    | '/api/games/$gameId/join'
    | '/api/games/$gameId/socket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScoreRoute: typeof ScoreRoute
  ApiGamesRoute: typeof ApiGamesRouteWithChildren
  GameGameIdRoute: typeof GameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games': {
      id: '/api/games'
      path: '/api/games'
      fullPath: '/api/games'
      preLoaderRoute: typeof ApiGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/join': {
      id: '/api/games/$gameId/join'
      path: '/$gameId/join'
      fullPath: '/api/games/$gameId/join'
      preLoaderRoute: typeof ApiGamesGameIdJoinRouteImport
      parentRoute: typeof ApiGamesRoute
    }
    '/api/games/$gameId/socket': {
      id: '/api/games/$gameId/socket'
      path: '/$gameId/socket'
      fullPath: '/api/games/$gameId/socket'
      preLoaderRoute: typeof ApiGamesGameIdSocketRouteImport
      parentRoute: typeof ApiGamesRoute
    }
  }
}

interface ApiGamesRouteChildren {
  ApiGamesGameIdJoinRoute: typeof ApiGamesGameIdJoinRoute
  ApiGamesGameIdSocketRoute: typeof ApiGamesGameIdSocketRoute
}

const ApiGamesRouteChildren: ApiGamesRouteChildren = {
  ApiGamesGameIdJoinRoute: ApiGamesGameIdJoinRoute,
  ApiGamesGameIdSocketRoute: ApiGamesGameIdSocketRoute,
}

const ApiGamesRouteWithChildren = ApiGamesRoute._addFileChildren(
  ApiGamesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScoreRoute: ScoreRoute,
  ApiGamesRoute: ApiGamesRouteWithChildren,
  GameGameIdRoute: GameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
